/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_prjmonument_NativeServer */

#ifndef _Included_com_example_prjmonument_NativeServer
#define _Included_com_example_prjmonument_NativeServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_prjmonument_NativeServer
 * Method:    nativeRes
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_example_prjmonument_NativeServer_nativeRes
  (JNIEnv *, jobject, jlong, jlong,jstring);

#ifdef __cplusplus
}
#endif
#endif
