/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_prjmonument_Imagelib */

#ifndef _Included_com_example_prjmonument_Imagelib
#define _Included_com_example_prjmonument_Imagelib
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_prjmonument_Imagelib_getNativeDescriptorsfromMat
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
